<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Conexao' => $baseDir . '/Models/Conexao.class.php',
    'Config' => $baseDir . '/Models/Config.class.php',
    'EasyPeasyICS' => $vendorDir . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
    'EnviarEmail' => $baseDir . '/Models/EnviarEmail.class.php',
    'Login' => $baseDir . '/Models/Login.class.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'PHPMailerOAuth' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauth.php',
    'PHPMailerOAuthGoogle' => $vendorDir . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'Rotas' => $baseDir . '/Models/Rotas.class.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'Sistema' => $baseDir . '/Models/Sistema.class.php',
    'Tasks' => $baseDir . '/Models/Task.class.php',
    'Template' => $baseDir . '/Models/Template.class.php',
    'User' => $baseDir . '/Models/User.class.php',
    'ntlm_sasl_client_class' => $vendorDir . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
