<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3b8002f5cbd9293ec048996d3da9f023
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $classMap = array (
        'Conexao' => __DIR__ . '/../..' . '/Models/Conexao.class.php',
        'Config' => __DIR__ . '/../..' . '/Models/Config.class.php',
        'EasyPeasyICS' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
        'EnviarEmail' => __DIR__ . '/../..' . '/Models/EnviarEmail.class.php',
        'Login' => __DIR__ . '/../..' . '/Models/Login.class.php',
        'PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
        'PHPMailerOAuth' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauth.php',
        'PHPMailerOAuthGoogle' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
        'POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.pop3.php',
        'Rotas' => __DIR__ . '/../..' . '/Models/Rotas.class.php',
        'SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.smtp.php',
        'Sistema' => __DIR__ . '/../..' . '/Models/Sistema.class.php',
        'Tasks' => __DIR__ . '/../..' . '/Models/Task.class.php',
        'Template' => __DIR__ . '/../..' . '/Models/Template.class.php',
        'User' => __DIR__ . '/../..' . '/Models/User.class.php',
        'ntlm_sasl_client_class' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
        'phpmailerException' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->classMap = ComposerStaticInit3b8002f5cbd9293ec048996d3da9f023::$classMap;

        }, null, ClassLoader::class);
    }
}
